// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Jellyfin.Plugin.TopTen.AcceptanceTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class TopTenCollectionFeature : object, global::Xunit.IClassFixture<TopTenCollectionFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Top Ten Collection", "  The plugin creates a collection of the most-watched movies and series\n  based o" +
                "n playback data within a configurable time window.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "TopTenCollection.feature"
#line hidden
        
        public TopTenCollectionFeature(TopTenCollectionFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("Features/TopTenCollection.feature", "Feature: Top Ten Collection\n\n  The plugin creates a collection of the most-watche" +
                    "d movies and series\n  based on playback data within a configurable time window.\n" +
                    "\n  Scenario: Movies ranked by unique user plays\n    Given a library with the fol" +
                    "lowing movies:\n      | Title          |\n      | Movie A        |\n      | Movie B" +
                    "        |\n      | Movie C        |\n    And the following users exist:\n      | Us" +
                    "ername |\n      | Alice    |\n      | Bob      |\n      | Charlie  |\n    And the fo" +
                    "llowing recent playback data:\n      | User    | Title   |\n      | Alice   | Movi" +
                    "e A |\n      | Bob     | Movie A |\n      | Charlie | Movie A |\n      | Alice   | " +
                    "Movie B |\n      | Bob     | Movie B |\n      | Alice   | Movie C |\n    When the T" +
                    "op Ten task executes\n    Then the collection should contain movies in this order" +
                    ":\n      | Title   |\n      | Movie A |\n      | Movie B |\n      | Movie C |\n\n  Sce" +
                    "nario: Old playback data is excluded\n    Given a library with the following movi" +
                    "es:\n      | Title          |\n      | Recent Movie   |\n      | Old Movie      |\n " +
                    "   And the following users exist:\n      | Username |\n      | Alice    |\n    And " +
                    "\"Recent Movie\" was played by \"Alice\" 5 days ago\n    And \"Old Movie\" was played b" +
                    "y \"Alice\" 60 days ago\n    And the days to consider is 30\n    When the Top Ten ta" +
                    "sk executes\n    Then the collection should contain \"Recent Movie\"\n    And the co" +
                    "llection should not contain \"Old Movie\"\n\n  Scenario: Collection respects configu" +
                    "red item count\n    Given a library with 20 movies all played recently\n    And th" +
                    "e top item count is set to 5\n    When the Top Ten task executes\n    Then the col" +
                    "lection should contain exactly 5 items\n\n  Scenario: Duplicate movies across libr" +
                    "aries are deduplicated\n    Given a library with movies sharing the same TMDB ID:" +
                    "\n      | Title         | Library | TMDB ID |\n      | Movie HD      | 1080p   | 1" +
                    "2345   |\n      | Movie 4K      | 4K      | 12345   |\n    And both copies have be" +
                    "en played recently\n    When the Top Ten task executes\n    Then the collection sh" +
                    "ould contain only one copy of the movie\n\n  Scenario: Old collection is cleaned u" +
                    "p when renamed\n    Given an existing collection named \"Old Top Ten\"\n    And the " +
                    "collection name is configured as \"New Top Ten\"\n    And the previous collection n" +
                    "ame was \"Old Top Ten\"\n    When the Top Ten task executes\n    Then the \"Old Top T" +
                    "en\" collection should be deleted\n    And the \"New Top Ten\" collection should exi" +
                    "st\n", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("Features/TopTenCollection.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "en-US", "Feature", "Top Ten Collection", "  The plugin creates a collection of the most-watched movies and series\n  based o" +
                        "n playback data within a configurable time window.", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Movies ranked by unique user plays", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a library with the following movies:", null, new global::Io.Cucumber.Messages.Types.DataTable(new global::Io.Cucumber.Messages.Types.Location(8, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableRow>(new global::Io.Cucumber.Messages.Types.TableRow[] {
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(8, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(8, new System.Nullable<long>(9)), "Title")}), "be99295f98cd3a54854b7bc9a2359aa0"),
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(9)), "Movie A")}), "4593dbb318ef48518627b4665ce1ea9f"),
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(9)), "Movie B")}), "ee7545b5180f2254b48093b338500f2f"),
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(11, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(11, new System.Nullable<long>(9)), "Movie C")}), "8a8df85479a41c509b2cb5f7c4116b75")})), "9564d58e48deba589779fbdcdf2ca04f"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the following users exist:", null, new global::Io.Cucumber.Messages.Types.DataTable(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableRow>(new global::Io.Cucumber.Messages.Types.TableRow[] {
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(9)), "Username")}), "7f871438b4ee6052961f05570352e30e"),
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(14, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(14, new System.Nullable<long>(9)), "Alice")}), "d127a82a6a349d5b822cfe67621212f5"),
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(9)), "Bob")}), "b669cf2de9ebf2549469c1748119ef6b"),
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(9)), "Charlie")}), "2502f30dbab8e15f9ab4789da971cbcc")})), "bd595cd4067a6457b08a09acc15af0b3"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the following recent playback data:", null, new global::Io.Cucumber.Messages.Types.DataTable(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableRow>(new global::Io.Cucumber.Messages.Types.TableRow[] {
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(9)), "User"),
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(19)), "Title")}), "2129c2da94a1f85eafd3d385aaf78c94"),
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(9)), "Alice"),
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(19)), "Movie A")}), "363e73b17aa977569840e1198f631054"),
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(9)), "Bob"),
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(19)), "Movie A")}), "db25d6d4cfc79c558f9c9baccc717c29"),
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(9)), "Charlie"),
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(19)), "Movie A")}), "4b0d21aed7e37d5395e714c620c8c57e"),
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(9)), "Alice"),
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(19)), "Movie B")}), "cd2beb79d55dfd50ab9c6bb090e0185c"),
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(9)), "Bob"),
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(19)), "Movie B")}), "32dc8e4ebf60a45f99eb22a305321929"),
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(9)), "Alice"),
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(19)), "Movie C")}), "d8d4d234ff899a56b7367958f8553a3d")})), "334492909a2f765db768ad45d32b7c55"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "the Top Ten task executes", null, null, "889990dcda36535bb4563e839c383d3d"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the collection should contain movies in this order:", null, new global::Io.Cucumber.Messages.Types.DataTable(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableRow>(new global::Io.Cucumber.Messages.Types.TableRow[] {
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(9)), "Title")}), "6c1aa215a3e5cc5dafc9c9d517d52b93"),
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(28, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(28, new System.Nullable<long>(9)), "Movie A")}), "5f26b5baa099d55d9c49afe626f7a2f0"),
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(29, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(29, new System.Nullable<long>(9)), "Movie B")}), "9985f45376f1c85e84a52fc4c289d8bd"),
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(30, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(30, new System.Nullable<long>(9)), "Movie C")}), "e6e11bd7e71700549671ae88d2058ab6")})), "6490822b79eda25d82e8e0e516c842ee")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "840a50f4086f5c5696de106d2e6d7f10")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(32, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Old playback data is excluded", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(33, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a library with the following movies:", null, new global::Io.Cucumber.Messages.Types.DataTable(new global::Io.Cucumber.Messages.Types.Location(34, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableRow>(new global::Io.Cucumber.Messages.Types.TableRow[] {
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(34, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(34, new System.Nullable<long>(9)), "Title")}), "e5ddc1042b7dcd518bf048fa02d477e8"),
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(35, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(35, new System.Nullable<long>(9)), "Recent Movie")}), "96551dd038b50155b1339e716c2f926f"),
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(36, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(36, new System.Nullable<long>(9)), "Old Movie")}), "87fd2f0d4cf36951b2c5f125757b0127")})), "0363edac96fed8519263fe9275d81466"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(37, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the following users exist:", null, new global::Io.Cucumber.Messages.Types.DataTable(new global::Io.Cucumber.Messages.Types.Location(38, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableRow>(new global::Io.Cucumber.Messages.Types.TableRow[] {
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(38, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(38, new System.Nullable<long>(9)), "Username")}), "403b62f64bb7ad55b8659320daa5d8f7"),
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(39, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(39, new System.Nullable<long>(9)), "Alice")}), "fc8092420c9dcf5ea13b360377f19be9")})), "977231b360cb6b5c8ea115a675dfe4d0"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(40, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "\"Recent Movie\" was played by \"Alice\" 5 days ago", null, null, "27e3cf0ee766e25ca24bc2d03358f121"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(41, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "\"Old Movie\" was played by \"Alice\" 60 days ago", null, null, "6e012cb0c1f4f75cb0b9b52870bf9c5d"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(42, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the days to consider is 30", null, null, "2dd43a4bdcdab55b88dc0e4b08184b5e"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(43, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "the Top Ten task executes", null, null, "0915c3ab39e9145d8a63a10bc3f562b9"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(44, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the collection should contain \"Recent Movie\"", null, null, "46dbd35b762a1d5996ffe9c6e1af6944"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(45, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the collection should not contain \"Old Movie\"", null, null, "e2c1f062c7422e5782340ecee13d1a43")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "8aaee3641dab6551bfdb80033ed6791b")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(47, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Collection respects configured item count", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(48, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a library with 20 movies all played recently", null, null, "75dc569c415143559bcd67ad0ae49c5b"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(49, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the top item count is set to 5", null, null, "8afd8b1d731aa35ebe17d9aa457c584f"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(50, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "the Top Ten task executes", null, null, "86beab3117cf2c5ea84ac5e603930054"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(51, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the collection should contain exactly 5 items", null, null, "6dba36266e2e2a539826c58dcdfcffd2")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "44ed392913b76d588047868846282a6e")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(53, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Duplicate movies across libraries are deduplicated", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(54, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a library with movies sharing the same TMDB ID:", null, new global::Io.Cucumber.Messages.Types.DataTable(new global::Io.Cucumber.Messages.Types.Location(55, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableRow>(new global::Io.Cucumber.Messages.Types.TableRow[] {
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(55, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(55, new System.Nullable<long>(9)), "Title"),
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(55, new System.Nullable<long>(25)), "Library"),
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(55, new System.Nullable<long>(35)), "TMDB ID")}), "83c5020956652d5888338e1c09fc24ec"),
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(56, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(56, new System.Nullable<long>(9)), "Movie HD"),
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(56, new System.Nullable<long>(25)), "1080p"),
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(56, new System.Nullable<long>(35)), "12345")}), "710e9f05ad99375bb32cd9f4dd8804d0"),
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(57, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(57, new System.Nullable<long>(9)), "Movie 4K"),
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(57, new System.Nullable<long>(25)), "4K"),
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(57, new System.Nullable<long>(35)), "12345")}), "77ccb344dfe5c05c8f4a4ebc15f65c63")})), "1ca655adbdbfbf50a79b93cb80c8fd2f"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(58, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "both copies have been played recently", null, null, "10ca77cd2fa9515a86172f445356cfc6"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(59, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "the Top Ten task executes", null, null, "7770289e117a1b5c904492791bb1e100"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(60, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the collection should contain only one copy of the movie", null, null, "ac8d0830797de652ad8a651a40a707e3")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "b5ca972cbf719657ad51da6569d6ab2e")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(62, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Old collection is cleaned up when renamed", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(63, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "an existing collection named \"Old Top Ten\"", null, null, "e73d956964b70f58ba2d8402c3aab279"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(64, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the collection name is configured as \"New Top Ten\"", null, null, "9dcfb22aad3d1251b8e49cfe9def3c03"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(65, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the previous collection name was \"Old Top Ten\"", null, null, "741d4f6c7aa20c51b7001fff533a9c3e"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(66, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "the Top Ten task executes", null, null, "b834b7b4a9eaf357b7d28b64b9468fad"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(67, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the \"Old Top Ten\" collection should be deleted", null, null, "0ebd241df3517f55b9b3e3ccad52d235"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(68, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the \"New Top Ten\" collection should exist", null, null, "db57bc253482cb54b41f948d0dd0daf9")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "7c77bd29d04e5057b91c17d5142094b7"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[0]));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("cd6bc402ae158957b59d26517a57c9a1", "Features/TopTenCollection.feature", "Movies ranked by unique user plays", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(new global::Io.Cucumber.Messages.Types.PickleStepArgument(null, new global::Io.Cucumber.Messages.Types.PickleTable(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableRow>(new global::Io.Cucumber.Messages.Types.PickleTableRow[] {
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Title")})),
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Movie A")})),
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Movie B")})),
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Movie C")}))}))), new System.Collections.Generic.List<string>(new string[] {
                                                        "9564d58e48deba589779fbdcdf2ca04f"}), "ad7d9fd48df5d55bb863ec7b881b042d", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a library with the following movies:"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(new global::Io.Cucumber.Messages.Types.PickleStepArgument(null, new global::Io.Cucumber.Messages.Types.PickleTable(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableRow>(new global::Io.Cucumber.Messages.Types.PickleTableRow[] {
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Username")})),
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Alice")})),
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Bob")})),
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Charlie")}))}))), new System.Collections.Generic.List<string>(new string[] {
                                                        "bd595cd4067a6457b08a09acc15af0b3"}), "50f3759bb535dc5c9051cf9767e07c83", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the following users exist:"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(new global::Io.Cucumber.Messages.Types.PickleStepArgument(null, new global::Io.Cucumber.Messages.Types.PickleTable(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableRow>(new global::Io.Cucumber.Messages.Types.PickleTableRow[] {
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("User"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Title")})),
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Alice"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Movie A")})),
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Bob"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Movie A")})),
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Charlie"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Movie A")})),
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Alice"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Movie B")})),
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Bob"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Movie B")})),
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Alice"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Movie C")}))}))), new System.Collections.Generic.List<string>(new string[] {
                                                        "334492909a2f765db768ad45d32b7c55"}), "00af3788729a705c81fa5006a103d1fd", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the following recent playback data:"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "889990dcda36535bb4563e839c383d3d"}), "27876d1f9b326f54aa437e425000c1f3", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the Top Ten task executes"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(new global::Io.Cucumber.Messages.Types.PickleStepArgument(null, new global::Io.Cucumber.Messages.Types.PickleTable(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableRow>(new global::Io.Cucumber.Messages.Types.PickleTableRow[] {
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Title")})),
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Movie A")})),
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Movie B")})),
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Movie C")}))}))), new System.Collections.Generic.List<string>(new string[] {
                                                        "6490822b79eda25d82e8e0e516c842ee"}), "6bdf8bd864071d56811a4dbee1d6a639", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the collection should contain movies in this order:")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "840a50f4086f5c5696de106d2e6d7f10"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("f80cb8d1a94a0b529cb98c497d877d56", "Features/TopTenCollection.feature", "Old playback data is excluded", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(new global::Io.Cucumber.Messages.Types.PickleStepArgument(null, new global::Io.Cucumber.Messages.Types.PickleTable(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableRow>(new global::Io.Cucumber.Messages.Types.PickleTableRow[] {
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Title")})),
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Recent Movie")})),
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Old Movie")}))}))), new System.Collections.Generic.List<string>(new string[] {
                                                        "0363edac96fed8519263fe9275d81466"}), "d9e338fcb9a8c953888b80f967117a6c", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a library with the following movies:"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(new global::Io.Cucumber.Messages.Types.PickleStepArgument(null, new global::Io.Cucumber.Messages.Types.PickleTable(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableRow>(new global::Io.Cucumber.Messages.Types.PickleTableRow[] {
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Username")})),
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Alice")}))}))), new System.Collections.Generic.List<string>(new string[] {
                                                        "977231b360cb6b5c8ea115a675dfe4d0"}), "7e4068d927325e518cf0529b118f8fac", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the following users exist:"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "27e3cf0ee766e25ca24bc2d03358f121"}), "f822074fa08bb153b71270a2033a3f28", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "\"Recent Movie\" was played by \"Alice\" 5 days ago"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "6e012cb0c1f4f75cb0b9b52870bf9c5d"}), "fca851e81ab5d35f99c09fdac17c5bde", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "\"Old Movie\" was played by \"Alice\" 60 days ago"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "2dd43a4bdcdab55b88dc0e4b08184b5e"}), "1b1cab4d7644275f9f23a0a5f3d3c955", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the days to consider is 30"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0915c3ab39e9145d8a63a10bc3f562b9"}), "919d306a74e4ca5986b7a24756f6dbcf", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the Top Ten task executes"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "46dbd35b762a1d5996ffe9c6e1af6944"}), "86c577fcbb2cda5ba0c961e319653f0c", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the collection should contain \"Recent Movie\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e2c1f062c7422e5782340ecee13d1a43"}), "d788716a1fc74857a52fa7bfea3e6304", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the collection should not contain \"Old Movie\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "8aaee3641dab6551bfdb80033ed6791b"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("22d9018a861dc350ad8803c6f9d6ad12", "Features/TopTenCollection.feature", "Collection respects configured item count", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "75dc569c415143559bcd67ad0ae49c5b"}), "fbb9e8611eb73058a225477ba9521779", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a library with 20 movies all played recently"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "8afd8b1d731aa35ebe17d9aa457c584f"}), "7899a7d1992d085f9cf5ed457187c9b8", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the top item count is set to 5"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "86beab3117cf2c5ea84ac5e603930054"}), "7efbc5e9bb14a858941e9d0725aa5f65", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the Top Ten task executes"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "6dba36266e2e2a539826c58dcdfcffd2"}), "d6c002eacb9c6e5ebb88b842e2386e38", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the collection should contain exactly 5 items")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "44ed392913b76d588047868846282a6e"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("118745e101c2f5589b528ba367c77141", "Features/TopTenCollection.feature", "Duplicate movies across libraries are deduplicated", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(new global::Io.Cucumber.Messages.Types.PickleStepArgument(null, new global::Io.Cucumber.Messages.Types.PickleTable(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableRow>(new global::Io.Cucumber.Messages.Types.PickleTableRow[] {
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Title"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Library"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("TMDB ID")})),
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Movie HD"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("1080p"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("12345")})),
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Movie 4K"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("4K"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("12345")}))}))), new System.Collections.Generic.List<string>(new string[] {
                                                        "1ca655adbdbfbf50a79b93cb80c8fd2f"}), "e71b2267ecd1755cab8e824e3f62e33e", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a library with movies sharing the same TMDB ID:"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "10ca77cd2fa9515a86172f445356cfc6"}), "1af318b47f6e7e5aafd105ed43ea6ec6", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "both copies have been played recently"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "7770289e117a1b5c904492791bb1e100"}), "ee75a4ae42c5ec508d86b7323cd504ac", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the Top Ten task executes"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ac8d0830797de652ad8a651a40a707e3"}), "53a6cf77bb781e50a90dfc71325d9740", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the collection should contain only one copy of the movie")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "b5ca972cbf719657ad51da6569d6ab2e"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("f24db04f9254fe5c8f844a7619749941", "Features/TopTenCollection.feature", "Old collection is cleaned up when renamed", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e73d956964b70f58ba2d8402c3aab279"}), "52d22d9f1651f755940a694c267571d6", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "an existing collection named \"Old Top Ten\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "9dcfb22aad3d1251b8e49cfe9def3c03"}), "ebc646735176df52ab7092e41f0f834a", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the collection name is configured as \"New Top Ten\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "741d4f6c7aa20c51b7001fff533a9c3e"}), "9e6ce8489d182c558a7c5cf832746c51", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the previous collection name was \"Old Top Ten\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "b834b7b4a9eaf357b7d28b64b9468fad"}), "1b1fa0dff363fe5085826378917e1806", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the Top Ten task executes"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0ebd241df3517f55b9b3e3ccad52d235"}), "ff6ab0b16d3dbe5b9fa130afc9332130", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the \"Old Top Ten\" collection should be deleted"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "db57bc253482cb54b41f948d0dd0daf9"}), "3338b34699a4e151a81f64be50ede227", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the \"New Top Ten\" collection should exist")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "7c77bd29d04e5057b91c17d5142094b7"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(TopTenCollectionFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(TopTenCollectionFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(TopTenCollectionFeature.PicklesFunc));
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Movies ranked by unique user plays")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Top Ten Collection")]
        [global::Xunit.TraitAttribute("Description", "Movies ranked by unique user plays")]
        public async global::System.Threading.Tasks.Task MoviesRankedByUniqueUserPlays()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Movies ranked by unique user plays", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 6
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Title"});
                table1.AddRow(new string[] {
                            "Movie A"});
                table1.AddRow(new string[] {
                            "Movie B"});
                table1.AddRow(new string[] {
                            "Movie C"});
#line 7
    await testRunner.GivenAsync("a library with the following movies:", ((string)(null)), table1, "Given ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Username"});
                table2.AddRow(new string[] {
                            "Alice"});
                table2.AddRow(new string[] {
                            "Bob"});
                table2.AddRow(new string[] {
                            "Charlie"});
#line 12
    await testRunner.AndAsync("the following users exist:", ((string)(null)), table2, "And ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "User",
                            "Title"});
                table3.AddRow(new string[] {
                            "Alice",
                            "Movie A"});
                table3.AddRow(new string[] {
                            "Bob",
                            "Movie A"});
                table3.AddRow(new string[] {
                            "Charlie",
                            "Movie A"});
                table3.AddRow(new string[] {
                            "Alice",
                            "Movie B"});
                table3.AddRow(new string[] {
                            "Bob",
                            "Movie B"});
                table3.AddRow(new string[] {
                            "Alice",
                            "Movie C"});
#line 17
    await testRunner.AndAsync("the following recent playback data:", ((string)(null)), table3, "And ");
#line hidden
#line 25
    await testRunner.WhenAsync("the Top Ten task executes", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Title"});
                table4.AddRow(new string[] {
                            "Movie A"});
                table4.AddRow(new string[] {
                            "Movie B"});
                table4.AddRow(new string[] {
                            "Movie C"});
#line 26
    await testRunner.ThenAsync("the collection should contain movies in this order:", ((string)(null)), table4, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Old playback data is excluded")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Top Ten Collection")]
        [global::Xunit.TraitAttribute("Description", "Old playback data is excluded")]
        public async global::System.Threading.Tasks.Task OldPlaybackDataIsExcluded()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Old playback data is excluded", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 32
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "Title"});
                table5.AddRow(new string[] {
                            "Recent Movie"});
                table5.AddRow(new string[] {
                            "Old Movie"});
#line 33
    await testRunner.GivenAsync("a library with the following movies:", ((string)(null)), table5, "Given ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "Username"});
                table6.AddRow(new string[] {
                            "Alice"});
#line 37
    await testRunner.AndAsync("the following users exist:", ((string)(null)), table6, "And ");
#line hidden
#line 40
    await testRunner.AndAsync("\"Recent Movie\" was played by \"Alice\" 5 days ago", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 41
    await testRunner.AndAsync("\"Old Movie\" was played by \"Alice\" 60 days ago", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 42
    await testRunner.AndAsync("the days to consider is 30", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 43
    await testRunner.WhenAsync("the Top Ten task executes", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 44
    await testRunner.ThenAsync("the collection should contain \"Recent Movie\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 45
    await testRunner.AndAsync("the collection should not contain \"Old Movie\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Collection respects configured item count")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Top Ten Collection")]
        [global::Xunit.TraitAttribute("Description", "Collection respects configured item count")]
        public async global::System.Threading.Tasks.Task CollectionRespectsConfiguredItemCount()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Collection respects configured item count", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 47
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 48
    await testRunner.GivenAsync("a library with 20 movies all played recently", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 49
    await testRunner.AndAsync("the top item count is set to 5", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 50
    await testRunner.WhenAsync("the Top Ten task executes", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 51
    await testRunner.ThenAsync("the collection should contain exactly 5 items", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Duplicate movies across libraries are deduplicated")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Top Ten Collection")]
        [global::Xunit.TraitAttribute("Description", "Duplicate movies across libraries are deduplicated")]
        public async global::System.Threading.Tasks.Task DuplicateMoviesAcrossLibrariesAreDeduplicated()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Duplicate movies across libraries are deduplicated", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 53
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "Title",
                            "Library",
                            "TMDB ID"});
                table7.AddRow(new string[] {
                            "Movie HD",
                            "1080p",
                            "12345"});
                table7.AddRow(new string[] {
                            "Movie 4K",
                            "4K",
                            "12345"});
#line 54
    await testRunner.GivenAsync("a library with movies sharing the same TMDB ID:", ((string)(null)), table7, "Given ");
#line hidden
#line 58
    await testRunner.AndAsync("both copies have been played recently", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 59
    await testRunner.WhenAsync("the Top Ten task executes", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 60
    await testRunner.ThenAsync("the collection should contain only one copy of the movie", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Old collection is cleaned up when renamed")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Top Ten Collection")]
        [global::Xunit.TraitAttribute("Description", "Old collection is cleaned up when renamed")]
        public async global::System.Threading.Tasks.Task OldCollectionIsCleanedUpWhenRenamed()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Old collection is cleaned up when renamed", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 62
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 63
    await testRunner.GivenAsync("an existing collection named \"Old Top Ten\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 64
    await testRunner.AndAsync("the collection name is configured as \"New Top Ten\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
    await testRunner.AndAsync("the previous collection name was \"Old Top Ten\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 66
    await testRunner.WhenAsync("the Top Ten task executes", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 67
    await testRunner.ThenAsync("the \"Old Top Ten\" collection should be deleted", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 68
    await testRunner.AndAsync("the \"New Top Ten\" collection should exist", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await TopTenCollectionFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await TopTenCollectionFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
